/* Generated By:JavaCC: Do not edit this line. CalculadoraConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CalculadoraConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 4;
  /** RegularExpression Id. */
  int DIGITS = 5;
  /** RegularExpression Id. */
  int MAIS = 6;
  /** RegularExpression Id. */
  int MENOS = 7;
  /** RegularExpression Id. */
  int DIVISAO = 8;
  /** RegularExpression Id. */
  int PRODUTO = 9;
  /** RegularExpression Id. */
  int ABRIR_PARENTESES = 10;
  /** RegularExpression Id. */
  int FECHAR_PARENTESES = 11;
  /** RegularExpression Id. */
  int EXP = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "<NUMBER>",
    "<DIGITS>",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"*\"",
    "\"(\"",
    "\")\"",
    "\"^\"",
  };

}
