/* Generated By:JavaCC: Do not edit this line. ERsConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ERsConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int AouB = 5;
  /** RegularExpression Id. */
  int EOL = 6;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<AouB>",
    "\";\"",
  };

}
